services:
  mysql:
    image: mysql:8
    ports:
      - '3310:3306'
    expose:
      - '3310'
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'gifts_development'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - '9200:9200'
    expose:
      - '9200'
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
volumes:
  mysql:
  elasticsearch:
